#! /usr/bin/env ruby

require 'io/console'
require 'matrix'
require 'date'
require 'byebug'

year = Date.today.year.to_s

problem = ARGV.shift
if problem.index("-").nil?
  year = problem
  problem = ARGV.shift
end

Dir.glob("lib/#{year}/*.rb").each do |file|
  require_relative file
end

klass_name = "D#{problem.sub("-", "P")}".to_sym
klass_name = "#{klass_name}::#{klass_name}"
input_file = File.join("inputs", year, ARGV.shift)

log_folder = File.join(__dir__, "logs", year.to_s)
Dir.mkdir(log_folder) unless Dir.exists?(log_folder)
$output_file = File.new(File.join(log_folder, "#{problem}.txt"), "w")

def $stdout.write string
  $output_file.write string
  super
end

klass = Object::const_get(klass_name)
problem = klass.new()
start_time  = Time.now
input = File.readlines(input_file)
input.map!{|line| line.strip} unless klass.const_defined?("NO_STRIP")
problem.run(input)
end_time  = Time.now

duration = (end_time - start_time)*1000
duration = (duration *100).round / 100.0

puts "Duration: #{duration}ms"
