#! /usr/bin/env ruby

require 'io/console'
require 'matrix'
require 'date'
require 'byebug'

year = Date.today.year
SESSION = File.read(File.join(__dir__, ".session_token")).strip

day = ARGV.shift
if day.length == 4
  year = day.to_i
  day = ARGV.shift
end

url = "https://adventofcode.com/#{year}/day/#{day}/input"

input_folder = File.join(__dir__, "inputs", year.to_s)
Dir.mkdir(input_folder) unless Dir.exist?(input_folder)
File.open(File.join(input_folder, "#{day}.txt"), "w") do |io|
  io.write `curl --cookie session=#{SESSION} #{url}`
end

lib_folder = File.join(__dir__, "lib", year.to_s)
Dir.mkdir(lib_folder) unless Dir.exist?(lib_folder)
["1", "2"].each do |problem|
  klass_name = "D#{day}P#{problem}".to_sym
  klass_name = "#{klass_name}::#{klass_name}"
  File.open(File.join(lib_folder, "#{day}-#{problem}.rb"), "w") do |io|
    io.puts "module D#{day}P#{problem}"
    io.puts "  class D#{day}P#{problem}"
    io.puts "    def run(input)"
    io.puts "    end"
    io.puts "  end"
    io.puts "end"
  end
end
